package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysButton generated by hbm2java
 */
@Entity
@Table(name = "sys_button", catalog = "powersh")
public class SysButton implements java.io.Serializable {

	private Integer btnId;
	private String btnName;
	private String btnNo;
	private String btnClass;
	private String btnIcon;
	private String btnScript;
	private String menuNo;
	private String initStatus;
	private Integer seqNo;

	public SysButton() {
	}

	public SysButton(String btnName, String btnNo, String btnClass,
			String btnIcon, String btnScript, String menuNo, String initStatus,
			Integer seqNo) {
		this.btnName = btnName;
		this.btnNo = btnNo;
		this.btnClass = btnClass;
		this.btnIcon = btnIcon;
		this.btnScript = btnScript;
		this.menuNo = menuNo;
		this.initStatus = initStatus;
		this.seqNo = seqNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BtnID", unique = true, nullable = false)
	public Integer getBtnId() {
		return this.btnId;
	}

	public void setBtnId(Integer btnId) {
		this.btnId = btnId;
	}

	@Column(name = "BtnName", length = 50)
	public String getBtnName() {
		return this.btnName;
	}

	public void setBtnName(String btnName) {
		this.btnName = btnName;
	}

	@Column(name = "BtnNo", length = 50)
	public String getBtnNo() {
		return this.btnNo;
	}

	public void setBtnNo(String btnNo) {
		this.btnNo = btnNo;
	}

	@Column(name = "BtnClass", length = 100)
	public String getBtnClass() {
		return this.btnClass;
	}

	public void setBtnClass(String btnClass) {
		this.btnClass = btnClass;
	}

	@Column(name = "BtnIcon", length = 100)
	public String getBtnIcon() {
		return this.btnIcon;
	}

	public void setBtnIcon(String btnIcon) {
		this.btnIcon = btnIcon;
	}

	@Column(name = "BtnScript", length = 100)
	public String getBtnScript() {
		return this.btnScript;
	}

	public void setBtnScript(String btnScript) {
		this.btnScript = btnScript;
	}

	@Column(name = "MenuNo", length = 100)
	public String getMenuNo() {
		return this.menuNo;
	}

	public void setMenuNo(String menuNo) {
		this.menuNo = menuNo;
	}

	@Column(name = "InitStatus", length = 100)
	public String getInitStatus() {
		return this.initStatus;
	}

	public void setInitStatus(String initStatus) {
		this.initStatus = initStatus;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

}
