package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysDepartment generated by hbm2java
 */
@Entity
@Table(name = "sys_department", catalog = "powersh")
public class SysDepartment implements java.io.Serializable {

	private String departmentId;
	private String departmentName;
	private String parentId;
	private String remark;

	public SysDepartment() {
	}

	public SysDepartment(String departmentId) {
		this.departmentId = departmentId;
	}

	public SysDepartment(String departmentId, String departmentName,
			String parentId, String remark) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.parentId = parentId;
		this.remark = remark;
	}

	@Id
	@Column(name = "department_id", unique = true, nullable = false, length = 30)
	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "department_name", length = 30)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "parent_id", length = 30)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
