package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysDict generated by hbm2java
 */
@Entity
@Table(name = "sys_dict", catalog = "powersh")
public class SysDict implements java.io.Serializable {

	private Integer dictId;
	private String dictNum;
	private String dictName;
	private Integer dictValue;
	private String dictText;

	public SysDict() {
	}

	public SysDict(String dictNum, String dictName, Integer dictValue,
			String dictText) {
		this.dictNum = dictNum;
		this.dictName = dictName;
		this.dictValue = dictValue;
		this.dictText = dictText;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dictID", unique = true, nullable = false)
	public Integer getDictId() {
		return this.dictId;
	}

	public void setDictId(Integer dictId) {
		this.dictId = dictId;
	}

	@Column(name = "dictNum", length = 50)
	public String getDictNum() {
		return this.dictNum;
	}

	public void setDictNum(String dictNum) {
		this.dictNum = dictNum;
	}

	@Column(name = "dictName", length = 50)
	public String getDictName() {
		return this.dictName;
	}

	public void setDictName(String dictName) {
		this.dictName = dictName;
	}

	@Column(name = "dictValue")
	public Integer getDictValue() {
		return this.dictValue;
	}

	public void setDictValue(Integer dictValue) {
		this.dictValue = dictValue;
	}

	@Column(name = "dictText", length = 50)
	public String getDictText() {
		return this.dictText;
	}

	public void setDictText(String dictText) {
		this.dictText = dictText;
	}

}
