package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysFunction generated by hbm2java
 */
@Entity
@Table(name = "sys_function", catalog = "powersh")
public class SysFunction implements java.io.Serializable {

	private String functionId;
	private SysModule sysModule;
	private String name;
	private String remark;
	private String callback;
	private String displayName;
	private String beforeCallback;
	private String afterCallback;
	private Integer status;
	private String sort;
	private String icon;

	public SysFunction() {
	}

	public SysFunction(String functionId) {
		this.functionId = functionId;
	}

	public SysFunction(String functionId, SysModule sysModule, String name,
			String remark, String callback, String displayName,
			String beforeCallback, String afterCallback, Integer status,
			String sort, String icon) {
		this.functionId = functionId;
		this.sysModule = sysModule;
		this.name = name;
		this.remark = remark;
		this.callback = callback;
		this.displayName = displayName;
		this.beforeCallback = beforeCallback;
		this.afterCallback = afterCallback;
		this.status = status;
		this.sort = sort;
		this.icon = icon;
	}

	@Id
	@Column(name = "function_id", unique = true, nullable = false, length = 30)
	public String getFunctionId() {
		return this.functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_id")
	public SysModule getSysModule() {
		return this.sysModule;
	}

	public void setSysModule(SysModule sysModule) {
		this.sysModule = sysModule;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "callback", length = 100)
	public String getCallback() {
		return this.callback;
	}

	public void setCallback(String callback) {
		this.callback = callback;
	}

	@Column(name = "Display_name", length = 30)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "before_callback", length = 100)
	public String getBeforeCallback() {
		return this.beforeCallback;
	}

	public void setBeforeCallback(String beforeCallback) {
		this.beforeCallback = beforeCallback;
	}

	@Column(name = "after_callback", length = 100)
	public String getAfterCallback() {
		return this.afterCallback;
	}

	public void setAfterCallback(String afterCallback) {
		this.afterCallback = afterCallback;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "sort", length = 30)
	public String getSort() {
		return this.sort;
	}

	public void setSort(String sort) {
		this.sort = sort;
	}

	@Column(name = "icon", length = 200)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

}
