package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.TableGenerator;


import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysMenu generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "sys_menu", catalog = "powersh")
public class SysMenu implements java.io.Serializable {

	private Integer menuId;
	private String menuNo;
	private String menuParentNo;
	private Integer menuOrder;
	private String menuName;
	private String menuUrl;
	private String menuIcon;
	private Integer isVisible;
	private Integer isLeaf;

	public SysMenu() {
	}

	public SysMenu(String menuNo, String menuParentNo, Integer menuOrder,
			String menuName, String menuUrl, String menuIcon,
			Integer isVisible, Integer isLeaf) {
		this.menuNo = menuNo;
		this.menuParentNo = menuParentNo;
		this.menuOrder = menuOrder;
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.menuIcon = menuIcon;
		this.isVisible = isVisible;
		this.isLeaf = isLeaf;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="MENU_SEQUENCE")
	@TableGenerator(name = "MENU_SEQUENCE",
	    table="sys_sequence",
	    pkColumnName="seqName",
	    valueColumnName="seqValue",
	    pkColumnValue="MENU_SEQUENCE",
	    allocationSize=1
	)
	@Column(name = "MenuID", unique = true, nullable = false)
	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	@Column(name = "MenuNo", length = 50)
	public String getMenuNo() {
		return this.menuNo;
	}

	public void setMenuNo(String menuNo) {
		this.menuNo = menuNo;
	}

	@Column(name = "MenuParentNo", length = 50)
	public String getMenuParentNo() {
		return this.menuParentNo;
	}

	public void setMenuParentNo(String menuParentNo) {
		this.menuParentNo = menuParentNo;
	}

	@Column(name = "MenuOrder")
	public Integer getMenuOrder() {
		return this.menuOrder;
	}

	public void setMenuOrder(Integer menuOrder) {
		this.menuOrder = menuOrder;
	}

	@Column(name = "MenuName", length = 50)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "MenuUrl", length = 200)
	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	@Column(name = "MenuIcon", length = 200)
	public String getMenuIcon() {
		return this.menuIcon;
	}

	public void setMenuIcon(String menuIcon) {
		this.menuIcon = menuIcon;
	}

	@Column(name = "IsVisible")
	public Integer getIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(Integer isVisible) {
		this.isVisible = isVisible;
	}

	@Column(name = "IsLeaf")
	public Integer getIsLeaf() {
		return this.isLeaf;
	}

	public void setIsLeaf(Integer isLeaf) {
		this.isLeaf = isLeaf;
	}

}
