package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysModule generated by hbm2java
 */
@Entity
@Table(name = "sys_module", catalog = "powersh")
public class SysModule implements java.io.Serializable {

	private String moduleId;
	private String moduleName;
	private String path;
	private Integer status;
	private String parentId;
	private String remark;
	private Integer isMenu;
	private String icon;
	private Set sysFunctions = new HashSet(0);

	public SysModule() {
	}

	public SysModule(String moduleId) {
		this.moduleId = moduleId;
	}

	public SysModule(String moduleId, String moduleName, String path,
			Integer status, String parentId, String remark, Integer isMenu,
			String icon, Set sysFunctions) {
		this.moduleId = moduleId;
		this.moduleName = moduleName;
		this.path = path;
		this.status = status;
		this.parentId = parentId;
		this.remark = remark;
		this.isMenu = isMenu;
		this.icon = icon;
		this.sysFunctions = sysFunctions;
	}

	@Id
	@Column(name = "module_id", unique = true, nullable = false, length = 30)
	public String getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "module_name", length = 30)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "path", length = 200)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "parent_id", length = 30)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "isMenu")
	public Integer getIsMenu() {
		return this.isMenu;
	}

	public void setIsMenu(Integer isMenu) {
		this.isMenu = isMenu;
	}

	@Column(name = "icon", length = 200)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysModule")
	public Set getSysFunctions() {
		return this.sysFunctions;
	}

	public void setSysFunctions(Set sysFunctions) {
		this.sysFunctions = sysFunctions;
	}

}
