package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysObjColumn generated by hbm2java
 */
@Entity
@Table(name = "sys_obj_column", catalog = "powersh")
public class SysObjColumn implements java.io.Serializable {

	private String colId;
	private String objId;
	private String columnName;
	private String remark;
	private String showName;

	public SysObjColumn() {
	}

	public SysObjColumn(String colId) {
		this.colId = colId;
	}

	public SysObjColumn(String colId, String objId, String columnName,
			String remark, String showName) {
		this.colId = colId;
		this.objId = objId;
		this.columnName = columnName;
		this.remark = remark;
		this.showName = showName;
	}

	@Id
	@Column(name = "Col_id", unique = true, nullable = false, length = 30)
	public String getColId() {
		return this.colId;
	}

	public void setColId(String colId) {
		this.colId = colId;
	}

	@Column(name = "Obj_id", length = 30)
	public String getObjId() {
		return this.objId;
	}

	public void setObjId(String objId) {
		this.objId = objId;
	}

	@Column(name = "Column_Name", length = 50)
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "Show_Name", length = 50)
	public String getShowName() {
		return this.showName;
	}

	public void setShowName(String showName) {
		this.showName = showName;
	}

}
