package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * SysOrg generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "sys_org", catalog = "powersh")
public class SysOrg implements java.io.Serializable {

	private Integer orgId;
	private String orgCode;
	private String orgNum;
	private String orgName;
	private String orgRemark;
	private String parentNo;
	private String orgOrder;
	private Integer isLeaf;

	public SysOrg() {
	}

	public SysOrg(Integer orgId) {
		this.orgId = orgId;
	}

	public SysOrg(Integer orgId, String orgCode, String orgNum, String orgName,
			String orgRemark, String parentNo, String orgOrder, Integer isLeaf) {
		this.orgId = orgId;
		this.orgCode = orgCode;
		this.orgNum = orgNum;
		this.orgName = orgName;
		this.orgRemark = orgRemark;
		this.parentNo = parentNo;
		this.orgOrder = orgOrder;
		this.isLeaf = isLeaf;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="ORG_SEQUENCE")
	@TableGenerator(name = "ORG_SEQUENCE",
	    table="sys_sequence",
	    pkColumnName="seqName",
	    valueColumnName="seqValue",
	    pkColumnValue="ORG_SEQUENCE",
	    allocationSize=1
	)
	@Column(name = "orgId", unique = true, nullable = false, length = 30)
	public Integer getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	@Column(name = "orgCode", length = 50)
	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	@Column(name = "orgNum", length = 50)
	public String getOrgNum() {
		return this.orgNum;
	}

	public void setOrgNum(String orgNum) {
		this.orgNum = orgNum;
	}

	@Column(name = "orgName", length = 50)
	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	@Column(name = "orgRemark", length = 100)
	public String getOrgRemark() {
		return this.orgRemark;
	}

	public void setOrgRemark(String orgRemark) {
		this.orgRemark = orgRemark;
	}

	@Column(name = "parentNo", length = 30)
	public String getParentNo() {
		return this.parentNo;
	}

	public void setParentNo(String parentNo) {
		this.parentNo = parentNo;
	}

	@Column(name = "orgOrder", length = 30)
	public String getOrgOrder() {
		return this.orgOrder;
	}

	public void setOrgOrder(String orgOrder) {
		this.orgOrder = orgOrder;
	}

	@Column(name = "isLeaf")
	public Integer getIsLeaf() {
		return this.isLeaf;
	}

	public void setIsLeaf(Integer isLeaf) {
		this.isLeaf = isLeaf;
	}

}
