package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysObjDefinition generated by hbm2java
 */
@Entity
@Table(name = "sys_obj_definition", catalog = "powersh")
public class SysObjDefinition implements java.io.Serializable {

	private String objId;
	private String tableName;
	private String remark;
	private String showName;

	public SysObjDefinition() {
	}

	public SysObjDefinition(String objId) {
		this.objId = objId;
	}

	public SysObjDefinition(String objId, String tableName, String remark,
			String showName) {
		this.objId = objId;
		this.tableName = tableName;
		this.remark = remark;
		this.showName = showName;
	}

	@Id
	@Column(name = "Obj_id", unique = true, nullable = false, length = 30)
	public String getObjId() {
		return this.objId;
	}

	public void setObjId(String objId) {
		this.objId = objId;
	}

	@Column(name = "Table_Name", length = 50)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "Show_Name", length = 50)
	public String getShowName() {
		return this.showName;
	}

	public void setShowName(String showName) {
		this.showName = showName;
	}

}
