package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysPrivilege generated by hbm2java
 */
@Entity
@Table(name = "sys_privilege", catalog = "powersh")
public class SysPrivilege implements java.io.Serializable {

	private Integer privilegeId;
	private String privilegeMaster;
	private String privilegeMasterKey;
	private String privilegeAccess;
	private String privilegeAccessKey;
	private String privilegeOperation;

	public SysPrivilege() {
	}

	public SysPrivilege(String privilegeMaster, String privilegeMasterKey,
			String privilegeAccess, String privilegeAccessKey,
			String privilegeOperation) {
		this.privilegeMaster = privilegeMaster;
		this.privilegeMasterKey = privilegeMasterKey;
		this.privilegeAccess = privilegeAccess;
		this.privilegeAccessKey = privilegeAccessKey;
		this.privilegeOperation = privilegeOperation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PrivilegeID", unique = true, nullable = false)
	public Integer getPrivilegeId() {
		return this.privilegeId;
	}

	public void setPrivilegeId(Integer privilegeId) {
		this.privilegeId = privilegeId;
	}

	@Column(name = "PrivilegeMaster", length = 30)
	public String getPrivilegeMaster() {
		return this.privilegeMaster;
	}

	public void setPrivilegeMaster(String privilegeMaster) {
		this.privilegeMaster = privilegeMaster;
	}

	@Column(name = "PrivilegeMasterKey", length = 30)
	public String getPrivilegeMasterKey() {
		return this.privilegeMasterKey;
	}

	public void setPrivilegeMasterKey(String privilegeMasterKey) {
		this.privilegeMasterKey = privilegeMasterKey;
	}

	@Column(name = "PrivilegeAccess", length = 30)
	public String getPrivilegeAccess() {
		return this.privilegeAccess;
	}

	public void setPrivilegeAccess(String privilegeAccess) {
		this.privilegeAccess = privilegeAccess;
	}

	@Column(name = "PrivilegeAccessKey", length = 30)
	public String getPrivilegeAccessKey() {
		return this.privilegeAccessKey;
	}

	public void setPrivilegeAccessKey(String privilegeAccessKey) {
		this.privilegeAccessKey = privilegeAccessKey;
	}

	@Column(name = "PrivilegeOperation", length = 30)
	public String getPrivilegeOperation() {
		return this.privilegeOperation;
	}

	public void setPrivilegeOperation(String privilegeOperation) {
		this.privilegeOperation = privilegeOperation;
	}

}
