package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysRule generated by hbm2java
 */
@Entity
@Table(name = "sys_rule", catalog = "powersh")
public class SysRule implements java.io.Serializable {

	private String ruleId;
	private String name;
	private Integer isPublic;
	private String remark;
	private Integer status;
	private String ruleData;
	private String objectName;
	private Set sysRuleDefines = new HashSet(0);

	public SysRule() {
	}

	public SysRule(String ruleId) {
		this.ruleId = ruleId;
	}

	public SysRule(String ruleId, String name, Integer isPublic, String remark,
			Integer status, String ruleData, String objectName,
			Set sysRuleDefines) {
		this.ruleId = ruleId;
		this.name = name;
		this.isPublic = isPublic;
		this.remark = remark;
		this.status = status;
		this.ruleData = ruleData;
		this.objectName = objectName;
		this.sysRuleDefines = sysRuleDefines;
	}

	@Id
	@Column(name = "rule_id", unique = true, nullable = false, length = 30)
	public String getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(String ruleId) {
		this.ruleId = ruleId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_public")
	public Integer getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Integer isPublic) {
		this.isPublic = isPublic;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "Rule_data", length = 500)
	public String getRuleData() {
		return this.ruleData;
	}

	public void setRuleData(String ruleData) {
		this.ruleData = ruleData;
	}

	@Column(name = "objectName", length = 100)
	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRule")
	public Set getSysRuleDefines() {
		return this.sysRuleDefines;
	}

	public void setSysRuleDefines(Set sysRuleDefines) {
		this.sysRuleDefines = sysRuleDefines;
	}

}
