package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role", catalog = "powersh")
public class SysRole implements java.io.Serializable {

	private String roleId;
	private String roleName;
	private String remark;
	private String status;
	private Set sysRoleUsers = new HashSet(0);

	public SysRole() {
	}

	public SysRole(String roleId) {
		this.roleId = roleId;
	}

	public SysRole(String roleId, String roleName, String remark,
			String status, Set sysRoleUsers) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.remark = remark;
		this.status = status;
		this.sysRoleUsers = sysRoleUsers;
	}

	@Id
	@Column(name = "role_id", unique = true, nullable = false, length = 30)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", length = 30)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "remark", length = 300)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "status", length = 4)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
	public Set getSysRoleUsers() {
		return this.sysRoleUsers;
	}

	public void setSysRoleUsers(Set sysRoleUsers) {
		this.sysRoleUsers = sysRoleUsers;
	}

}
