package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysSequenceBak generated by hbm2java
 */
@Entity
@Table(name = "sys_sequence_bak", catalog = "powersh")
public class SysSequenceBak implements java.io.Serializable {

	private String seqNum;
	private String seqName;
	private Long seqValue;
	private String seqPrefix;
	private String seqSuffix;
	private Integer seqLength;
	private String seqFill;
	private Integer seqAdd;
	private String seqLastValue;

	public SysSequenceBak() {
	}

	public SysSequenceBak(String seqNum) {
		this.seqNum = seqNum;
	}

	public SysSequenceBak(String seqNum, String seqName, Long seqValue,
			String seqPrefix, String seqSuffix, Integer seqLength,
			String seqFill, Integer seqAdd, String seqLastValue) {
		this.seqNum = seqNum;
		this.seqName = seqName;
		this.seqValue = seqValue;
		this.seqPrefix = seqPrefix;
		this.seqSuffix = seqSuffix;
		this.seqLength = seqLength;
		this.seqFill = seqFill;
		this.seqAdd = seqAdd;
		this.seqLastValue = seqLastValue;
	}

	@Id
	@Column(name = "seqNum", unique = true, nullable = false, length = 50)
	public String getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(String seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "seqName", length = 50)
	public String getSeqName() {
		return this.seqName;
	}

	public void setSeqName(String seqName) {
		this.seqName = seqName;
	}

	@Column(name = "seqValue")
	public Long getSeqValue() {
		return this.seqValue;
	}

	public void setSeqValue(Long seqValue) {
		this.seqValue = seqValue;
	}

	@Column(name = "seqPrefix", length = 25)
	public String getSeqPrefix() {
		return this.seqPrefix;
	}

	public void setSeqPrefix(String seqPrefix) {
		this.seqPrefix = seqPrefix;
	}

	@Column(name = "seqSuffix", length = 25)
	public String getSeqSuffix() {
		return this.seqSuffix;
	}

	public void setSeqSuffix(String seqSuffix) {
		this.seqSuffix = seqSuffix;
	}

	@Column(name = "seqLength")
	public Integer getSeqLength() {
		return this.seqLength;
	}

	public void setSeqLength(Integer seqLength) {
		this.seqLength = seqLength;
	}

	@Column(name = "seqFill", length = 2)
	public String getSeqFill() {
		return this.seqFill;
	}

	public void setSeqFill(String seqFill) {
		this.seqFill = seqFill;
	}

	@Column(name = "seqAdd")
	public Integer getSeqAdd() {
		return this.seqAdd;
	}

	public void setSeqAdd(Integer seqAdd) {
		this.seqAdd = seqAdd;
	}

	@Column(name = "seqLastValue", length = 30)
	public String getSeqLastValue() {
		return this.seqLastValue;
	}

	public void setSeqLastValue(String seqLastValue) {
		this.seqLastValue = seqLastValue;
	}

}
