package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysSequence generated by hbm2java
 */
@Entity
@Table(name = "sys_sequence", catalog = "powersh")
public class SysSequence implements java.io.Serializable {

	private String seqNum;
	private String seqName;
	private String seqValue;

	public SysSequence() {
	}

	public SysSequence(String seqNum) {
		this.seqNum = seqNum;
	}

	public SysSequence(String seqNum, String seqName, String seqValue) {
		this.seqNum = seqNum;
		this.seqName = seqName;
		this.seqValue = seqValue;
	}

	@Id
	@Column(name = "seqNum", unique = true, nullable = false, length = 50)
	public String getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(String seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "seqName", length = 50)
	public String getSeqName() {
		return this.seqName;
	}

	public void setSeqName(String seqName) {
		this.seqName = seqName;
	}

	@Column(name = "seqValue", length = 50)
	public String getSeqValue() {
		return this.seqValue;
	}

	public void setSeqValue(String seqValue) {
		this.seqValue = seqValue;
	}

}
