package com.power.core.security.entity;

// Generated 2014-1-2 10:46:56 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysUser generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "sys_user", catalog = "powersh")
public class SysUser implements java.io.Serializable {

	private String userId;
	private String userName;
	private String password;
	private String orgId;
	private Date userBirthDay;
	private String userPhone;
	private String userEmail;
	private Integer status;
	private String remark;
	private Integer userOrder;

	public SysUser() {
	}

	public SysUser(String userId) {
		this.userId = userId;
	}

	public SysUser(String userId, String userName, String password,
			String orgId, Date userBirthDay, String userPhone,
			String userEmail, Integer status, String remark, Integer userOrder) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.orgId = orgId;
		this.userBirthDay = userBirthDay;
		this.userPhone = userPhone;
		this.userEmail = userEmail;
		this.status = status;
		this.remark = remark;
		this.userOrder = userOrder;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="USER_SEQUENCE")
	@TableGenerator(name = "USER_SEQUENCE",
	    table="sys_sequence",
	    pkColumnName="seqName",
	    valueColumnName="seqValue",
	    pkColumnValue="USER_SEQUENCE",
	    allocationSize=1
	)
	@Column(name = "userId", unique = true, nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "userName", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "orgId", length = 20)
	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "userBirthDay", length = 0)
	public Date getUserBirthDay() {
		return this.userBirthDay;
	}

	public void setUserBirthDay(Date userBirthDay) {
		this.userBirthDay = userBirthDay;
	}

	@Column(name = "userPhone", length = 11)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "userEmail", length = 20)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "UserOrder")
	public Integer getUserOrder() {
		return this.userOrder;
	}

	public void setUserOrder(Integer userOrder) {
		this.userOrder = userOrder;
	}

}
