package com.power.core.security.entity;

// Generated 2013-12-25 16:25:53 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysUserBak generated by hbm2java
 */
@Entity
@Table(name = "sys_user_bak", catalog = "powersh")
public class SysUserBak implements java.io.Serializable {

	private String userId;
	private String loginName;
	private String password;
	private String orgId;
	private String nickname;
	private Integer status;
	private Integer passwordStatus;
	private String remark;
	private Set sysRoleUsers = new HashSet(0);

	public SysUserBak() {
	}

	public SysUserBak(String userId) {
		this.userId = userId;
	}

	public SysUserBak(String userId, String loginName, String password,
			String orgId, String nickname, Integer status,
			Integer passwordStatus, String remark, Set sysRoleUsers) {
		this.userId = userId;
		this.loginName = loginName;
		this.password = password;
		this.orgId = orgId;
		this.nickname = nickname;
		this.status = status;
		this.passwordStatus = passwordStatus;
		this.remark = remark;
		this.sysRoleUsers = sysRoleUsers;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, length = 30)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "login_name", length = 30)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "password", length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "orgId", length = 30)
	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Column(name = "nickname", length = 30)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "password_status")
	public Integer getPasswordStatus() {
		return this.passwordStatus;
	}

	public void setPasswordStatus(Integer passwordStatus) {
		this.passwordStatus = passwordStatus;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUserBak")
	public Set getSysRoleUsers() {
		return this.sysRoleUsers;
	}

	public void setSysRoleUsers(Set sysRoleUsers) {
		this.sysRoleUsers = sysRoleUsers;
	}

}
