package com.power.core.security.entity;

// Generated 2014-1-2 10:44:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbGenerator generated by hbm2java
 */
@Entity
@Table(name = "tb_generator", catalog = "powersh")
public class TbGenerator implements java.io.Serializable {

	private String id;
	private String genName;
	private String genValue;

	public TbGenerator() {
	}

	public TbGenerator(String id, String genName, String genValue) {
		this.id = id;
		this.genName = genName;
		this.genValue = genValue;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "gen_name", nullable = false)
	public String getGenName() {
		return this.genName;
	}

	public void setGenName(String genName) {
		this.genName = genName;
	}

	@Column(name = "gen_value", nullable = false, length = 25)
	public String getGenValue() {
		return this.genValue;
	}

	public void setGenValue(String genValue) {
		this.genValue = genValue;
	}

}
